workflows:
  windows-build:
    name: Build Windows App
    environment:
      node: latest  # or use 'latest' if you want the latest version
    scripts:
      - npm install
      # Download NuGet
      - curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      - mono nuget.exe restore windows/React-Native.sln  # Replace {AppName} with your app's name
      - cd windows
      # Build the app using MSBuild
      - msbuild /p:Configuration=Release /p:Platform=x64 React-Native.sln
    artifacts:
      - windows/x64/Release/React-Native/React-Native.exe
