workflows:
  windows-build:
    name: Build Windows App
    environment:
      node: 20.x
    scripts:
      - npm install
      - npx react-native-windows-init --overwrite
      - cd windows
      - nuget restore
      - msbuild /p:Configuration=Release /p:Platform=x64 {AppName}.sln
    artifacts:
      - windows/x64/Release/AppName/AppName.exe
