workflows:
  windows-build:
    name: Windows Build
    environment:
      node: 18.x
      os: windows
      react-native-windows: true
    scripts:
      - npm install
      - npm run windows --release
    artifacts:
      - windows/x64/Release/AppName/AppName.exe
